// navigation
export const PUSH_ROUTE = 'PUSH_ROUTE';
export const POP_ROUTE = 'POP_ROUTE';
// sign in
export const SIGN_IN = 'SIGN_IN';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_ERROR = 'SIGNIN_ERROR';
//Search accounts
export const SEARCH = 'SEARCH';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAIL = 'SEARCH_FAIL';
export const PUSH_ACCOUNT_DETAIL = 'PUSH_ACCOUNT_DETAIL';
// devices
export const GET_DEVICES = 'GET_DEVICES';
export const GET_DEVICES_SUCCESS = 'GET_DEVICES_SUCCESS';
export const GET_DEVICES_FAIL = 'GET_DEVICES_FAIL';

export const PUSH_ADD_DEVICE = 'PUSH_ADD_DEVICE';
export const PUSH_DEVICE_LIST = 'PUSH_DEVICE_LIST';
export const PUSH_DEVICE_LIST_DEMO = 'PUSH_DEVICE_LIST_DEMO';
export const PUSH_SHOW_DEVICE = 'PUSH_SHOW_DEVICE';

export const PUSH_SHOW_BLOCKS = 'PUSH_SHOW_BLOCKS';

export const PUSH_SHOW_BLOCK = 'PUSH_SHOW_BLOCK';
export const PUSH_SHOW_BLOCKS_LIST = 'PUSH_SHOW_BLOCKS_LIST';
export const PUSH_SHOW_BLOCKS_PROPERTY = 'PUSH_SHOW_BLOCKS_PROPERTY';
export const PUSH_SHOW_BLOCK_DETAILS = 'PUSH_SHOW_BLOCK_DETAILS';
export const PUSH_FLOWMETER = 'PUSH_FLOWMETER';

export const CLEAR_SEARCH     = 'CLEAR_SEARCH';
export const SAVE_GATEWAY_DETAILS     = 'SAVE_GATEWAY_DETAILS';

//creation of vineyard
export const SAVE_VINEYARD= 'SAVE_VINEYARD';
export const GET_VINEYARD_SUCCESS = 'GET_VINEYARD_SUCCESS';
export const GET_VINEYARD_FAIL = 'GET_VINEYARD_FAIL';


export const SAVE_VIN_DEVICE  =  'SAVE_VIN_DEVICE';
export const SAVE_VIN_DEVICE_SUCCESS  =  'SAVE_VIN_DEVICE_SUCCESS';
export const SAVE_VIN_DEVICE_FAIL  =  'SAVE_VIN_DEVICE_FAIL';


export const UPDATE_VIN_DEVICE  =  'UPDATE_VIN_DEVICE';
export const UPDATE_VIN_DEVICE_SUCCESS  =  'UPDATE_VIN_DEVICE_SUCCESS';
export const UPDATE_VIN_DEVICE_FAIL  =  'UPDATE_VIN_DEVICE_FAIL';

export const DELETE_DEVICE  = 'DELETE_DEVICE';
export const DELETE_DEVICE_SUCCESS = 'DELETE_DEVICE_SUCCESS';
export const DELETE_DEVICE_FAIL  = 'DELETE_DEVICE_FAIL';




export const PUSH_GATE_WEATHER_DEVICE     = 'PUSH_GATE_WEATHER_DEVICE';

//creation of blocks
export const SAVE_BLOCK_DEVICE  ='SAVE_BLOCK_DEVICE';
export const SAVE_BLOCK_DEVICE_SUCCESS ='SAVE_BLOCK_DEVICE_SUCCESS';
export const SAVE_BLOCK_DEVICE_FAIL = 'SAVE_BLOCK_DEVICE_FAIL';

export const UPDATE_BLOCK_DEVICE  =  'UPDATE_BLOCK_DEVICE';
export const UPDATE_BLOCK_DEVICE_SUCCESS = 'UPDATE_BLOCK_DEVICE_SUCCESS';
export const UPDATE_BLOCK_DEVICE_FAIL  =  'UPDATE_BLOCK_DEVICE_FAIL';

export const CREATE_BLOCK = 'CREATE_BLOCK';
export const CREATE_BLOCK_SUCCESS = 'CREATE_BLOCK_SUCCESS';
export const CREATE_BLOCK_FAIL = 'CREATE_BLOCK_FAIL';


//Block Properties
export const SAVE_BLOCK_PARAMETER         = 'SAVE_BLOCK_PARAMETER';
export const SAVE_BLOCK_PARAMETER_SUCCESS = 'SAVE_BLOCK_PARAMETER_SUCCESS';
export const SAVE_BLOCK_PARAMETER_FAIL    = 'SAVE_BLOCK_PARAMETER_FAIL';

export const SAVE_BLOCK_PRODUCTION_OBJ         = 'SAVE_BLOCK_PRODUCTION_OBJ';
export const SAVE_BLOCK_PRODUCTION_OBJ_SUCCESS = 'SAVE_BLOCK_PRODUCTION_OBJ_SUCCESS';
export const SAVE_BLOCK_PRODUCTION_OBJ_FAIL    = 'SAVE_BLOCK_PRODUCTION_OBJ_FAIL';

export const SAVE_BLOCK_SOIL_INFO         = 'SAVE_BLOCK_SOIL_INFO';
export const SAVE_BLOCK_SOIL_INFO_SUCCESS = 'SAVE_BLOCK_SOIL_INFO_SUCCESS';
export const SAVE_BLOCK_SOIL_INFO_FAIL    = 'SAVE_BLOCK_SOIL_INFO_FAIL';


export const SAVE_BLOCK_ANNUAL_VAR         = 'SAVE_BLOCK_ANNUAL_VAR';
export const SAVE_BLOCK_ANNUAL_VAR_SUCCESS = 'SAVE_BLOCK_ANNUAL_VAR_SUCCESS';
export const SAVE_BLOCK_ANNUAL_VAR_FAIL    = 'SAVE_BLOCK_ANNUAL_VAR_FAIL';

export const SAVE_BLOCK_KEY_DATES         = 'SAVE_BLOCK_KEY_DATES';
export const SAVE_BLOCK_KEY_DATES_SUCCESS = 'SAVE_BLOCK_KEY_DATES_SUCCESS';
export const SAVE_BLOCK_KEY_DATES_FAIL    = 'SAVE_BLOCK_KEY_DATES_FAIL';

// update block paramebers

export const UPDATE_BLOCK_PARAMETER         = 'UPDATE_BLOCK_PARAMETER';
export const UPDATE_BLOCK_PARAMETER_SUCCESS = 'UPDATE_BLOCK_PARAMETER_SUCCESS';
export const UPDATE_BLOCK_PARAMETER_FAIL    = 'UPDATE_BLOCK_PARAMETER_FAIL';

export const UPDATE_BLOCK_PRODUCTION_OBJ         = 'UPDATE_BLOCK_PRODUCTION_OBJ';
export const UPDATE_BLOCK_PRODUCTION_OBJ_SUCCESS = 'UPDATE_BLOCK_PRODUCTION_OBJ_SUCCESS';
export const UPDATE_BLOCK_PRODUCTION_OBJ_FAIL    = 'UPDATE_BLOCK_PRODUCTION_OBJ_FAIL';

export const UPDATE_BLOCK_SOIL_INFO         = 'UPDATE_BLOCK_SOIL_INFO';
export const UPDATE_BLOCK_SOIL_INFO_SUCCESS = 'UPDATE_BLOCK_SOIL_INFO_SUCCESS';
export const UPDATE_BLOCK_SOIL_INFO_FAIL    = 'UPDATE_BLOCK_SOIL_INFO_FAIL';


export const UPDATE_BLOCK_ANNUAL_VAR         = 'UPDATE_BLOCK_ANNUAL_VAR';
export const UPDATE_BLOCK_ANNUAL_VAR_SUCCESS = 'UPDATE_BLOCK_ANNUAL_VAR_SUCCESS';
export const UPDATE_BLOCK_ANNUAL_VAR_FAIL    = 'UPDATE_BLOCK_ANNUAL_VAR_FAIL';

export const UPDATE_BLOCK_KEY_DATES         = 'UPDATE_BLOCK_KEY_DATES';
export const UPDATE_BLOCK_KEY_DATES_SUCCESS = 'UPDATE_BLOCK_KEY_DATES_SUCCESS';
export const UPDATE_BLOCK_KEY_DATES_FAIL    = 'UPDATE_BLOCK_KEY_DATES_FAIL';



export const DELETE_BLOCK  = 'DELETE_BLOCK';
export const DELETE_BLOCK_SUCCESS = 'DELETE_BLOCK_SUCCESS';
export const DELETE_BLOCK_FAIL  = 'DELETE_BLOCK_FAIL';



export const SEARCH_PROFILE     = 'SEARCH_PROFILE';


// orders
export const GET_ORDERS = 'GET_ORDERS';
// map
export const DISPLAY_MAP = 'DISPLAY_MAP';
export const GET_POLYGON_SUCCESS = 'GET_POLYGON_SUCCESS';
export const GET_POLYGON_FAIL = 'GET_POLYGON_FAIL';

export const SAVE_MAP = 'SAVE_MAP';
export const MAP_SAVE_SUCCESS = 'MAP_SAVE_SUCCESS';
export const MAP_SAVE_FAIL = 'MAP_SAVE_FAIL';
export const PUSH_VINEYARD_DETAIL= 'PUSH_VINEYARD_DETAIL';

export const DEVICE_MAP = 'DEVICE_MAP';
export const PUSH_BLOCK_MAP = 'PUSH_BLOCK_MAP';
export const SAVE_BLOCK_MAP = 'SAVE_BLOCK_MAP';
// list
export const HEADER_CLICK = 'HEADER_CLICK';
